# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rlzLaBxDsKELfkRePTQmpRXeTWvA2_US
"""

import rospy
from std_srvs.srv import Empty

rospy.init_node('main_node')

rospy.wait_for_service('/go_to_kitchen')
go_to_kitchen = rospy.ServiceProxy('/go_to_kitchen', Empty)
go_to_kitchen()  # Call the /go_to_kitchen service

rospy.wait_for_service('/stop')
stop = rospy.ServiceProxy('/stop', Empty)
stop()  # Call the /stop service

rospy.wait_for_service('/go_home')
go_home = rospy.ServiceProxy('/go_home', Empty)
go_home()  # Call the /go_home service

stop()  # Call the /stop service again